version: "3.7"
services:
  app:
    build:
      args:
        user: yo
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    image: lsp-image
    container_name: lsp-container
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - lsp

  db:
    restart: unless-stopped
    image: mysql:8.0
    container_name: lsp-db-container
    environment:
      MYSQL_DATABASE: lsp
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1
     # MYSQL_PASSWORD: ${DB_PASSWORD}
     # MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - lsp

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: lsp-nginx-container
    ports:
      - 8000:80
      - 443:443
    depends_on:
      - db
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lsp

networks:
  lsp:
    driver: bridge

volumes:
  dbdata:
    driver: local
